---

version: 3

images:
  base_image:
    name: docker.io/library/ubuntu:20.04@sha256:e5a6aeef391a8a9bdaee3de6b28f393837c479d8217324a2340b64e45a81e0ef

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
  - python3.10
  - python3.10-pip
  python_interpreter:
    package_system: "python3.10"
    python_path: "/usr/bin/python3"
  galaxy:
    collections:
    - name: community.postgresql
    - name: community.general

additional_build_steps:
  prepend_builder: |
    RUN alternatives --set python3 /usr/bin/python3.10
    RUN python3 --version  # Verify Python 3.10 is the default

options:
  package_manager_path: /usr/bin/apt
