---

version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8@sha256:256b1b675262b4608a5f03e68287a90030d331e7f395da4e48cf89615f358920

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
  galaxy:
    collections:
    - name: community.postgresql

options:
  package_manager_path: /usr/bin/microdnf
